# Building the Multi-Year London Dataset

## Objective

Build a clean multi-year London property transaction dataset (2018–2025)
from the HM Land Registry Price Paid Data.

This dataset will serve as the foundation for all subsequent feature
engineering, borough-level aggregation, and machine learning models.

## Workflow

HM Land Registry Price Paid Data (2018–2025)

↓

Merge yearly datasets

↓

Filter Greater London transactions

↓

Save processed dataset

## Output

The processed dataset will be saved as:

`data/processed/london_transactions_2018_2025.csv`

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
# Project folders

RAW_DATA = Path("../data/raw")
PROCESSED_DATA = Path("../data/processed")

print("Raw folder:", RAW_DATA)
print("Processed folder:", PROCESSED_DATA)

Raw folder: ..\data\raw
Processed folder: ..\data\processed

In [3]:
# List all CSV files

csv_files = sorted(RAW_DATA.glob("*.csv"))

print(f"Number of files found: {len(csv_files)}")

for file in csv_files:
    print(file.name)

Number of files found: 11
borough_crime_historical.csv
borough_ptai_2015.csv
london_borough_area.csv
pp-2018.csv
pp-2019.csv
pp-2020.csv
pp-2021.csv
pp-2022.csv
pp-2023.csv
pp-2024.csv
pp-2025.csv

In [4]:
# Official HM Land Registry column names

column_names = [
    "Transaction unique identifier",
    "Price",
    "Date of Transfer",
    "Postcode",
    "Property Type",
    "Old/New",
    "Duration",
    "PAON",
    "SAON",
    "Street",
    "Locality",
    "Town/City",
    "District",
    "County",
    "PPD Category Type",
    "Record Status"
]

In [5]:
# Read one sample file

sample_file = csv_files[0]

df = pd.read_csv(
    sample_file,
    header=None,
    names=column_names
)

df.head()

                                                                                                                                                                                                                                                                                                                Transaction unique identifier  \
Group                     SubGroup                        BOCU                 202007 202008 202009 202010 202011 202012 202101 202102 202103 202104 202105 202106 202107 202108 202109 202110 202111 202112 202201 202202 202203 202204 202205 202206 202207 202208 202209 202210 202211 202212 202301 202302                         202303
ARSON AND CRIMINAL DAMAGE ARSON                           Barking and Dagenham 4      6      2      7      4      2      4      6      5      6      5      5      3      12     5      7      5      1      3      3      2      5      6      5      9      5      4      4      3      1      3      3                                   2
                          CRIMINAL DAMAGE                 Barking and Dagenham 122    113    114    120    99     110    100    103    81     100    122    137    126    140    112    120    105    114    123    107    111    124    111    136    112    127    100    138    101    91     93     91                                110
BURGLARY                  BURGLARY BUSINESS AND COMMUNITY Barking and Dagenham 28     23     32     18     18     24     20     18     13     11     28     24     21     28     25     37     20     14     18     28     27     15     15     23     18     27     29     25     21     21     27     18                                 32
                          DOMESTIC BURGLARY               Barking and Dagenham 72     62     55     67     89     92     69     90     71     74     78     66     59     85     56     82     82     92     78     65     73     79     70     51     44     72     75     78     64     84     91     38                                 55

                                                                                                                                                                                                                                                                                                                 Price  \
Group                     SubGroup                        BOCU                 202007 202008 202009 202010 202011 202012 202101 202102 202103 202104 202105 202106 202107 202108 202109 202110 202111 202112 202201 202202 202203 202204 202205 202206 202207 202208 202209 202210 202211 202212 202301 202302  202304
ARSON AND CRIMINAL DAMAGE ARSON                           Barking and Dagenham 4      6      2      7      4      2      4      6      5      6      5      5      3      12     5      7      5      1      3      3      2      5      6      5      9      5      4      4      3      1      3      3            2
                          CRIMINAL DAMAGE                 Barking and Dagenham 122    113    114    120    99     110    100    103    81     100    122    137    126    140    112    120    105    114    123    107    111    124    111    136    112    127    100    138    101    91     93     91          97
BURGLARY                  BURGLARY BUSINESS AND COMMUNITY Barking and Dagenham 28     23     32     18     18     24     20     18     13     11     28     24     21     28     25     37     20     14     18     28     27     15     15     23     18     27     29     25     21     21     27     18          36
                          DOMESTIC BURGLARY               Barking and Dagenham 72     62     55     67     89     92     69     90     71     74     78     66     59     85     56     82     82     92     78     65     73     79     70     51     44     72     75     78     64     84     91     38          48

                                                                                                                                                                                                                                                                                                                Date of Transfer  \
Group                     SubGroup                        BOCU                 202007 202008 202009 202010 202011 202012 202101 202102 202103 202104 202105 202106 202107 202108 202109 202110 202111 202112 202201 202202 202203 202204 202205 202206 202207 202208 202209 202210 202211 202212 202301 202302            202305
ARSON AND CRIMINAL DAMAGE ARSON                           Barking and Dagenham 4      6      2      7      4      2      4      6      5      6      5      5      3      12     5      7      5      1      3      3      2      5      6      5      9      5      4      4      3      1      3      3                      5
                          CRIMINAL DAMAGE                 Barking and Dagenham 122    113    114    120    99     110    100    103    81     100    122    137    126    140    112    120    105    114    123    107    111    124    111    136    112    127    100    138    101    91     93     91                   108
BURGLARY                  BURGLARY BUSINESS AND COMMUNITY Barking and Dagenham 28     23     32     18     18     24     20     18     13     11     28     24     21     28     25     37     20     14     18     28     27     15     15     23     18     27     29     25     21     21     27     18                    27
                          DOMESTIC BURGLARY               Barking and Dagenham 72     62     55     67     89     92     69     90     71     74     78     66     59     85     56     82     82     92     78     65     73     79     70     51     44     72     75     78     64     84     91     38                     0

                                                                                                                                                                                                                                                                                                                Postcode  \
Group                     SubGroup                        BOCU                 202007 202008 202009 202010 202011 202012 202101 202102 202103 202104 202105 202106 202107 202108 202109 202110 202111 202112 202201 202202 202203 202204 202205 202206 202207 202208 202209 202210 202211 202212 202301 202302    202306
ARSON AND CRIMINAL DAMAGE ARSON                           Barking and Dagenham 4      6      2      7      4      2      4      6      5      6      5      5      3      12     5      7      5      1      3      3      2      5      6      5      9      5      4      4      3      1      3      3              2
                          CRIMINAL DAMAGE                 Barking and Dagenham 122    113    114    120    99     110    100    103    81     100    122    137    126    140    112    120    105    114    123    107    111    124    111    136    112    127    100    138    101    91     93     91           122
BURGLARY                  BURGLARY BUSINESS AND COMMUNITY Barking and Dagenham 28     23     32     18     18     24     20     18     13     11     28     24     21     28     25     37     20     14     18     28     27     15     15     23     18     27     29     25     21     21     27     18            28
                          DOMESTIC BURGLARY               Barking and Dagenham 72     62     55     67     89     92     69     90     71     74     78     66     59     85     56     82     82     92     78     65     73     79     70     51     44     72     75     78     64     84     91     38             1

                                                                                                                                                                                                                                                                                                                Property Type  \
Group                     SubGroup                        BOCU                 202007 202008 202009 202010 202011 202012 202101 202102 202103 202104 202105 202106 202107 202108 202109 202110 202111 202112 202201 202202 202203 202204 202205 202206 202207 202208 202209 202210 202211 202212 202301 202302         202307
ARSON AND CRIMINAL DAMAGE ARSON                           Barking and Dagenham 4      6      2      7      4      2      4      6      5      6      5      5      3      12     5      7      5      1      3      3      2      5      6      5      9      5      4      4      3      1      3      3                   5
                          CRIMINAL DAMAGE                 Barking and Dagenham 122    113    114    120    99     110    100    103    81     100    122    137    126    140    112    120    105    114    123    107    111    124    111    136    112    127    100    138    101    91     93     91                131
BURGLARY                  BURGLARY BUSINESS AND COMMUNITY Barking and Dagenham 28     23     32     18     18     24     20     18     13     11     28     24     21     28     25     37     20     14     18     28     27     15     15     23     18     27     29     25     21     21     27     18                 25
                          DOMESTIC BURGLARY               Barking and Dagenham 72     62     55     67     89     92     69     90     71     74     78     66     59     85     56     82     82     92     78     65     73     79     70     51     44     72     75     78     64     84     91     38                  1

                                                                                                                                                                                                                                                                                                                Old/New  \
Group                     SubGroup                        BOCU                 202007 202008 202009 202010 202011 202012 202101 202102 202103 202104 202105 202106 202107 202108 202109 202110 202111 202112 202201 202202 202203 202204 202205 202206 202207 202208 202209 202210 202211 202212 202301 202302   202308
ARSON AND CRIMINAL DAMAGE ARSON                           Barking and Dagenham 4      6      2      7      4      2      4      6      5      6      5      5      3      12     5      7      5      1      3      3      2      5      6      5      9      5      4      4      3      1      3      3             7
                          CRIMINAL DAMAGE                 Barking and Dagenham 122    113    114    120    99     110    100    103    81     100    122    137    126    140    112    120    105    114    123    107    111    124    111    136    112    127    100    138    101    91     93     91          114
BURGLARY                  BURGLARY BUSINESS AND COMMUNITY Barking and Dagenham 28     23     32     18     18     24     20     18     13     11     28     24     21     28     25     37     20     14     18     28     27     15     15     23     18     27     29     25     21     21     27     18           34
                          DOMESTIC BURGLARY               Barking and Dagenham 72     62     55     67     89     92     69     90     71     74     78     66     59     85     56     82     82     92     78     65     73     79     70     51     44     72     75     78     64     84     91     38            0

                                                                                                                                                                                                                                                                                                                Duration  \
Group                     SubGroup                        BOCU                 202007 202008 202009 202010 202011 202012 202101 202102 202103 202104 202105 202106 202107 202108 202109 202110 202111 202112 202201 202202 202203 202204 202205 202206 202207 202208 202209 202210 202211 202212 202301 202302    202309
ARSON AND CRIMINAL DAMAGE ARSON                           Barking and Dagenham 4      6      2      7      4      2      4      6      5      6      5      5      3      12     5      7      5      1      3      3      2      5      6      5      9      5      4      4      3      1      3      3              4
                          CRIMINAL DAMAGE                 Barking and Dagenham 122    113    114    120    99     110    100    103    81     100    122    137    126    140    112    120    105    114    123    107    111    124    111    136    112    127    100    138    101    91     93     91           128
BURGLARY                  BURGLARY BUSINESS AND COMMUNITY Barking and Dagenham 28     23     32     18     18     24     20     18     13     11     28     24     21     28     25     37     20     14     18     28     27     15     15     23     18     27     29     25     21     21     27     18            38
                          DOMESTIC BURGLARY               Barking and Dagenham 72     62     55     67     89     92     69     90     71     74     78     66     59     85     56     82     82     92     78     65     73     79     70     51     44     72     75     78     64     84     91     38             0

                                                                                                                                                                                                                                                                                                                  PAON  \
Group                     SubGroup                        BOCU                 202007 202008 202009 202010 202011 202012 202101 202102 202103 202104 202105 202106 202107 202108 202109 202110 202111 202112 202201 202202 202203 202204 202205 202206 202207 202208 202209 202210 202211 202212 202301 202302  202310
ARSON AND CRIMINAL DAMAGE ARSON                           Barking and Dagenham 4      6      2      7      4      2      4      6      5      6      5      5      3      12     5      7      5      1      3      3      2      5      6      5      9      5      4      4      3      1      3      3            4
                          CRIMINAL DAMAGE                 Barking and Dagenham 122    113    114    120    99     110    100    103    81     100    122    137    126    140    112    120    105    114    123    107    111    124    111    136    112    127    100    138    101    91     93     91          82
BURGLARY                  BURGLARY BUSINESS AND COMMUNITY Barking and Dagenham 28     23     32     18     18     24     20     18     13     11     28     24     21     28     25     37     20     14     18     28     27     15     15     23     18     27     29     25     21     21     27     18          26
                          DOMESTIC BURGLARY               Barking and Dagenham 72     62     55     67     89     92     69     90     71     74     78     66     59     85     56     82     82     92     78     65     73     79     70     51     44     72     75     78     64     84     91     38           0

                                                                                                                                                                                                                                                                                                                  SAON  \
Group                     SubGroup                        BOCU                 202007 202008 202009 202010 202011 202012 202101 202102 202103 202104 202105 202106 202107 202108 202109 202110 202111 202112 202201 202202 202203 202204 202205 202206 202207 202208 202209 202210 202211 202212 202301 202302  202311
ARSON AND CRIMINAL DAMAGE ARSON                           Barking and Dagenham 4      6      2      7      4      2      4      6      5      6      5      5      3      12     5      7      5      1      3      3      2      5      6      5      9      5      4      4      3      1      3      3            3
                          CRIMINAL DAMAGE                 Barking and Dagenham 122    113    114    120    99     110    100    103    81     100    122    137    126    140    112    120    105    114    123    107    111    124    111    136    112    127    100    138    101    91     93     91          88
BURGLARY                  BURGLARY BUSINESS AND COMMUNITY Barking and Dagenham 28     23     32     18     18     24     20     18     13     11     28     24     21     28     25     37     20     14     18     28     27     15     15     23     18     27     29     25     21     21     27     18          19
                          DOMESTIC BURGLARY               Barking and Dagenham 72     62     55     67     89     92     69     90     71     74     78     66     59     85     56     82     82     92     78     65     73     79     70     51     44     72     75     78     64     84     91     38           0

                                                                                                                                                                                                                                                                                                                Street  \
Group                     SubGroup                        BOCU                 202007 202008 202009 202010 202011 202012 202101 202102 202103 202104 202105 202106 202107 202108 202109 202110 202111 202112 202201 202202 202203 202204 202205 202206 202207 202208 202209 202210 202211 202212 202301 202302  202312
ARSON AND CRIMINAL DAMAGE ARSON                           Barking and Dagenham 4      6      2      7      4      2      4      6      5      6      5      5      3      12     5      7      5      1      3      3      2      5      6      5      9      5      4      4      3      1      3      3            4
                          CRIMINAL DAMAGE                 Barking and Dagenham 122    113    114    120    99     110    100    103    81     100    122    137    126    140    112    120    105    114    123    107    111    124    111    136    112    127    100    138    101    91     93     91         125
BURGLARY                  BURGLARY BUSINESS AND COMMUNITY Barking and Dagenham 28     23     32     18     18     24     20     18     13     11     28     24     21     28     25     37     20     14     18     28     27     15     15     23     18     27     29     25     21     21     27     18          20
                          DOMESTIC BURGLARY               Barking and Dagenham 72     62     55     67     89     92     69     90     71     74     78     66     59     85     56     82     82     92     78     65     73     79     70     51     44     72     75     78     64     84     91     38           0

                                                                                                                                                                                                                                                                                                                Locality  \
Group                     SubGroup                        BOCU                 202007 202008 202009 202010 202011 202012 202101 202102 202103 202104 202105 202106 202107 202108 202109 202110 202111 202112 202201 202202 202203 202204 202205 202206 202207 202208 202209 202210 202211 202212 202301 202302    202401
ARSON AND CRIMINAL DAMAGE ARSON                           Barking and Dagenham 4      6      2      7      4      2      4      6      5      6      5      5      3      12     5      7      5      1      3      3      2      5      6      5      9      5      4      4      3      1      3      3              4

In [6]:
print(sample_file.name)

borough_crime_historical.csv

In [7]:
# Read all yearly files

dataframes = []

for file in csv_files:

    # Read file
    df = pd.read_csv(
        file,
        header=None,
        names=column_names
    )

    # Extract year from filename
    year = int(file.stem.split("-")[1])

    # Add Year column
    df["Year"] = year

    # Save DataFrame
    dataframes.append(df)

    print(f"{file.name} -> {len(df):,} rows")

IndexError: list index out of range

In [ ]:
print(len(dataframes))

8

In [ ]:
transactions_all_years = pd.concat(
    dataframes,
    ignore_index=True
)

In [ ]:
print(transactions_all_years.shape)

(8001857, 17)

In [ ]:
transactions_all_years.head()

,Transaction unique identifier,Price,Date of Transfer,Postcode,Property Type,Old/New,Duration,PAON,SAON,Street,Locality,Town/City,District,County,PPD Category Type,Record Status,Year
0,{79A74E21-D11E-1289-E053-6B04A8C01627},770000,2018-09-25 00:00,SK7 1AR,D,N,F,5,NaN,OAK MEADOW,BRAMHALL,STOCKPORT,STOCKPORT,GREATER MANCHESTER,A,A,2018
1,{79A74E21-D11F-1289-E053-6B04A8C01627},253500,2018-09-24 00:00,M6 8GQ,D,N,F,1,NaN,RIVINGTON ROAD,NaN,SALFORD,SALFORD,GREATER MANCHESTER,A,A,2018
2,{79A74E21-D120-1289-E053-6B04A8C01627},231950,2018-09-28 00:00,WA3 2UE,D,Y,F,35,NaN,STONEACRE CLOSE,LOWTON,WARRINGTON,WIGAN,GREATER MANCHESTER,A,A,2018
3,{79A74E21-D121-1289-E053-6B04A8C01627},112500,2018-08-29 00:00,OL6 6RJ,S,N,F,102,NaN,THORNFIELD GROVE,NaN,ASHTON-UNDER-LYNE,TAMESIDE,GREATER MANCHESTER,A,A,2018
4,{79A74E21-D122-1289-E053-6B04A8C01627},184995,2018-06-15 00:00,M46 0TW,S,Y,F,37,NaN,THREADNEEDLE PLACE,ATHERTON,MANCHESTER,WIGAN,GREATER MANCHESTER,A,A,2018

In [ ]:
transactions_all_years["Year"].value_counts().sort_index()

Year
2018    1037578
2019    1012107
2020     897433
2021    1281442
2022    1076492
2023     860609
2024     928502
2025     907694
Name: count, dtype: int64

In [ ]:
# Filter Greater London transactions

london_transactions = transactions_all_years[
    transactions_all_years["County"] == "GREATER LONDON"
].copy()

NameError: name 'transactions_all_years' is not defined

In [ ]:
print(f"Number of London transactions: {len(london_transactions):,}")

Number of London transactions: 887,229

In [ ]:
london_transactions.head()

,Transaction unique identifier,Price,Date of Transfer,Postcode,Property Type,Old/New,Duration,PAON,SAON,Street,Locality,Town/City,District,County,PPD Category Type,Record Status,Year
1108,{75050A85-94A3-9A88-E053-6B04A8C02390},354000,2018-08-03 00:00,BR6 0TR,T,N,F,8,NaN,COWDEN ROAD,NaN,ORPINGTON,BROMLEY,GREATER LONDON,A,A,2018
1109,{75050A85-94A4-9A88-E053-6B04A8C02390},392000,2018-07-27 00:00,KT6 5BH,F,N,L,36,FLAT 2,HOOK ROAD,NaN,SURBITON,KINGSTON UPON THAMES,GREATER LONDON,A,A,2018
1110,{75050A85-94A5-9A88-E053-6B04A8C02390},545000,2018-08-24 00:00,SW17 0PS,T,N,F,137,NaN,STRATHDON DRIVE,NaN,LONDON,WANDSWORTH,GREATER LONDON,A,A,2018
1111,{75050A85-94A6-9A88-E053-6B04A8C02390},269000,2018-06-29 00:00,BR6 6AX,T,N,F,22,NaN,KINGSLEY ROAD,NaN,ORPINGTON,BROMLEY,GREATER LONDON,A,A,2018
1112,{75050A85-94A7-9A88-E053-6B04A8C02390},335000,2018-08-16 00:00,DA7 5QZ,S,N,F,36,NaN,KING HAROLDS WAY,NaN,BEXLEYHEATH,BEXLEY,GREATER LONDON,A,A,2018

In [ ]:
# Save processed London dataset

output_file = PROCESSED_DATA / "london_transactions_2018_2025.csv"

london_transactions.to_csv(
    output_file,
    index=False
)

print(f"Saved to:\n{output_file}")

NameError: name 'london_transactions' is not defined