In [11]:
import pandas as pd

df_income = pd.read_excel("../data/raw/borough_income_taxpayers.xlsx")

df_income.head()

        Name HMRC Survey of Personal Incomes  Unnamed: 2 Unnamed: 3
0  ShortName                             SPI         NaN        NaN
1        NaN                             NaN         NaN        NaN
2        NaN                             NaN         NaN        NaN
3        NaN                             NaN         NaN        NaN
4      Theme           Employment and Skills         NaN        NaN

In [12]:
import os

os.listdir("../data/raw")

['borough_crime_historical.csv',
 'borough_income_taxpayers.xlsx',
 'borough_ptai_2015.csv',
 'pp-2018.csv',
 'pp-2019.csv',
 'pp-2020.csv',
 'pp-2021.csv',
 'pp-2022.csv',
 'pp-2023.csv',
 'pp-2024.csv',
 'pp-2025.csv']

In [13]:
excel_file = pd.ExcelFile("../data/raw/borough_income_taxpayers.xlsx")

excel_file.sheet_names

['Metadata', 'Total Income']

In [14]:
import pandas as pd

df_income = pd.read_excel(
    "../data/raw/borough_income_taxpayers.xlsx",
    sheet_name="Total Income"
)

df_income.head()

,Unnamed: 0,Unnamed: 1,1999-00,Unnamed: 3,Unnamed: 4,2000-01,Unnamed: 6,Unnamed: 7,2001-02,Unnamed: 9,...,Unnamed: 64,2021-22,Unnamed: 66,Unnamed: 67,2022-23,Unnamed: 69,Unnamed: 70,2023-24,Unnamed: 72,Unnamed: 73
0,Code,Area,Number of Individuals,Mean £,Median £,Number of Individuals,Mean £,Median £,Number of Individuals,Mean £,...,Median £,Number of Individuals,Mean £,Median £,Number of Individuals,Mean £,Median £,Number of Individuals,Mean £,Median £
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E09000001,City of London,10000,109800,40400,10000,137000,65000,12000,92900,...,56700,9000,167000,62200,11000,147000,60700,11000,162000,70000
3,E09000002,Barking and Dagenham,62000,16200,15100,71000,18100,15600,56000,18600,...,26800,90000,31800,28000,98000,33300,28600,106000,34600,29400
4,E09000003,Barnet,161000,26800,18700,156000,30800,19400,159000,30400,...,32200,190000,59100,33500,198000,59800,34400,216000,61600,36100

In [16]:
df_income = pd.read_excel(
    "../data/raw/borough_income_taxpayers.xlsx",
    sheet_name="Total Income",
    header=[0, 1]
)

df_income.head()

  Unnamed: 0_level_0    Unnamed: 1_level_0               1999-00            \
                Code                  Area Number of Individuals    Mean £
0                NaN                   NaN                   NaN       NaN
1          E09000001        City of London               10000.0  109800.0
2          E09000002  Barking and Dagenham               62000.0   16200.0
3          E09000003                Barnet              161000.0   26800.0
4          E09000004                Bexley              105000.0   20500.0

                         2000-01                                  2001-02  \
  Median £ Number of Individuals    Mean £ Median £ Number of Individuals
0      NaN                   NaN       NaN      NaN                   NaN
1  40400.0               10000.0  137000.0  65000.0               12000.0
2  15100.0               71000.0   18100.0  15600.0               56000.0
3  18700.0              156000.0   30800.0  19400.0              159000.0
4  17200.0              116000.0   19800.0  17300.0              112000.0

            ...  2020-21               2021-22                     \
    Mean £  ... Median £ Number of Individuals    Mean £ Median £
0      NaN  ...      NaN                   NaN       NaN      NaN
1  92900.0  ...  56700.0                9000.0  167000.0  62200.0
2  18600.0  ...  26800.0               90000.0   31800.0  28000.0
3  30400.0  ...  32200.0              190000.0   59100.0  33500.0
4  22000.0  ...  28800.0              135000.0   38000.0  29300.0

                2022-23                                  2023-24            \
  Number of Individuals    Mean £ Median £ Number of Individuals    Mean £
0                   NaN       NaN      NaN                   NaN       NaN
1               11000.0  147000.0  60700.0               11000.0  162000.0
2               98000.0   33300.0  28600.0              106000.0   34600.0
3              198000.0   59800.0  34400.0              216000.0   61600.0
4              134000.0   40900.0  31800.0              142000.0   42600.0


  Median £
0      NaN
1  70000.0
2  29400.0
3  36100.0
4  33200.0

[5 rows x 74 columns]